site_name: Visual Paradigm User Documentation

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Introduction: index.md
  - Creating New Diagram: Creating_new_diagram.md
  - Creating Shapes and Lines: Creating_shapes_and_lines.md
  - Downloading PDF of Diagram: Downloading_PDF_of_diagram.md
  - Troubleshooting: Troubleshooting.md
  - Glossary: Glossary.md
